package com.example.catovacka;

import java.util.ArrayList;
import java.util.List;

public class countries {
    public static List<String>list = new ArrayList<>();

    public static void pridanie()
    {
        list.add("Afghanistan +93");
        list.add("Albania +355");
        list.add("Algeria +213");
        list.add("Andorra +376");
        list.add("Angola +244");
        list.add("Antigua and Barbuda +1268");
        list.add("Argentina +54");
        list.add("Armenia +374");
        list.add("Australia +61");
        list.add("Austria +43");
        list.add("Azerbaijan +994");
        list.add("Bahamas +1242");
        list.add("Bahrain +973");
        list.add("Bangladesh +880");
        list.add("Barbados +1246");
        list.add("Belarus +375");
        list.add("Belgium +32");
        list.add("Belize +501");
        list.add("Benin +229");
        list.add("Bhutan +975");
        list.add("Bolivia +591");
        list.add("Bosnia and Herzegovina +387");
        list.add("Botswana +267");
        list.add("Brazil +55");
        list.add("Brunei +673");
        list.add("Bulgaria +359");
        list.add("Burkina Faso +226");
        list.add("Burundi +257");
        list.add("Cambodia +855");
        list.add("Cameroon +237");
        list.add("Canada +1");
        list.add("Cape Verde +238");
        list.add("Central African Republic +236");
        list.add("Chad +235");
        list.add("Chile +56");
        list.add("China +86");
        list.add("Colombia +57");
        list.add("Comoros +269");
        list.add("Congo, Democratic Republic +243");
        list.add("Congo, Republic +242");
        list.add("Costa Rica +506");
        list.add("Cote d'Ivoire +225");
        list.add("Croatia +385");
        list.add("Cuba +53");
        list.add("Cyprus +357");
        list.add("Czech Republic +420");
        list.add("Denmark +45");
        list.add("Djibouti +253");
        list.add("Dominica +1767");
        list.add("Dominican Republic +1809");
        list.add("East Timor +670");
        list.add("Ecuador +593");
        list.add("Egypt +20");
        list.add("El Salvador +503");
        list.add("Equatorial Guinea +240");
        list.add("Eritrea +291");
        list.add("Estonia +372");
        list.add("Ethiopia +251");
        list.add("Federated States of Micronesia +691");
        list.add("Fiji +679");
        list.add("Finland +358");
        list.add("France +33");
        list.add("Gabon +241");
        list.add("Gambia +220");
        list.add("Georgia +995");
        list.add("Germany +49");
        list.add("Ghana +233");
        list.add("Greece +30");
        list.add("Grenada +1473");
        list.add("Guatemala +502");
        list.add("Guinea +224");
        list.add("Guinea-Bissau +245");
        list.add("Guyana +592");
        list.add("Haiti +509");
        list.add("Honduras +504");
        list.add("Hungary +36");
        list.add("Iceland +354");
        list.add("India +91");
        list.add("Indonesia +62");
        list.add("Iran +98");
        list.add("Iraq +964");
        list.add("Ireland +353");
        list.add("Israel +972");
        list.add("Italy +39");
        list.add("Jamaica +1876");
        list.add("Japan +81");
        list.add("Jordan +962");
        list.add("Kazakhstan +77");
        list.add("Kenya +254");
        list.add("Kiribati +686");
        list.add("Kuwait +965");
        list.add("Kyrgyzstan +996");
        list.add("Laos +856");
        list.add("Latvia +371");
        list.add("Lebanon +961");
        list.add("Lesotho +266");
        list.add("Liberia +231");
        list.add("Libya +218");
        list.add("Liechtenstein +423");
        list.add("Lithuania +370");
        list.add("Luxembourg +352");
        list.add("Macedonia +389");
        list.add("Madagascar +261");
        list.add("Malawi +265");
        list.add("Malaysia +60");
        list.add("Maldives +960");
        list.add("Mali +223");
        list.add("Malta +356");
        list.add("Marshall Islands +692");
        list.add("Mauritania +222");
        list.add("Mauritius +230");
        list.add("Mexico +52");
        list.add("Moldova +373");
        list.add("Monaco +377");
        list.add("Mongolia +976");
        list.add("Montenegro +381");
        list.add("Morocco +212");
        list.add("Mozambique +259");
        list.add("Myanmar +95");
        list.add("Namibia +264");
        list.add("Nauru +674");
        list.add("Nepal +977");
        list.add("Netherlands +31");
        list.add("New Zealand +64");
        list.add("Nicaragua +505");
        list.add("Niger +227");
        list.add("Nigeria +234");
        list.add("North Korea +850");
        list.add("Norway +47");
        list.add("Oman +968");
        list.add("Pakistan +92");
        list.add("Palau +680");
        list.add("Panama +507");
        list.add("Papua New Guinea +675");
        list.add("Paraguay +595");
        list.add("Peru +51");
        list.add("Philippines +63");
        list.add("Poland +48");
        list.add("Portugal +351");
        list.add("Qatar +974");
        list.add("Romania +40");
        list.add("Russia +7");
        list.add("Rwanda +250");
        list.add("S?o Tom? and Pr?ncipe +239");
        list.add("Saint Kitts and Nevis +1869");
        list.add("Saint Lucia +1758");
        list.add("Saint Vincent and the Grenadines +1784");
        list.add("Samoa +685");
        list.add("San Marino +378");
        list.add("Saudi Arabia +966");
        list.add("Senegal +221");
        list.add("Serbia +381");
        list.add("Seychelles +248");
        list.add("Sierra Leone +232");
        list.add("Singapore +65");
        list.add("Slovakia +421");
        list.add("Slovenia +986");
        list.add("Solomon Islands +677");
        list.add("Somalia +252");
        list.add("South Africa +27");
        list.add("South Korea +82");
        list.add("Spain +34");
        list.add("Sri Lanka +94");
        list.add("Sudan +249");
        list.add("Suriname +597");
        list.add("Swaziland +268");
        list.add("Sweden +46");
        list.add("Switzerland +41");
        list.add("Syria +963");
        list.add("Tajikistan +992");
        list.add("Tanzania +255");
        list.add("Thailand +66");
        list.add("Togo +228");
        list.add("Tonga +676");
        list.add("Trinidad and Tobago +1868");
        list.add("Tunisia +216");
        list.add("Turkey +90");
        list.add("Turkmenistan +993");
        list.add("Tuvalu +688");
        list.add("Uganda +256");
        list.add("Ukraine +380");
        list.add("United Arab Emirates +971");
        list.add("United Kingdom +44");
        list.add("United States +1");
        list.add("Uruguay +598");
        list.add("Uzbekistan +998");
        list.add("Vanuatu +678");
        list.add("Vatican City +39");
        list.add("Venezuela +58");
        list.add("Vietnam +84");
        list.add("Yemen +967");
        list.add("Zambia +260");
        list.add("Zimbabwe +263");
    }

}
